from __future__ import annotations


NEW_DAY = "✨"
DETAILS = "■"
NO_DETAILS = "□"
TASK_STATUS = "⬢"
LIST = "•"
SUCCESS = "✔"
INFO = "ℹ"  # noqa: RUF001
WARNING = "▼"
ERROR = "✘"
NOTIFICATION = ">"
PROMPT = "?"
PROGRESSBAR = "▮"
PROGRESSBAR_EMPTY = "▯"
HISTORY_NODE = "├──"
HISTORY_END_NODE = "└──"

EMPTY_DETAILS = "..."
MULTILINES_DETAILS_START = "┌"
MULTILINES_DETAILS_MIDDLE = "│"
MULTILINES_DETAILS_END = "└"
